[mcp_servers.promptliano]
command = "bun"
args = ["run", "-C", "/Users/brandon/Programming/promptliano/packages/server", "mcp"]
env = { "PROMPTLIANO_PROJECT_ID" = "1", "PROMPTLIANO_PROJECT_PATH" = "/Users/brandon/Programming/promptliano", "PROMPTLIANO_API_URL" = "http://localhost:3147/api/mcp", "NODE_ENV" = "production" }


[mcp_severs.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest]
