# Package Configuration for Monorepo CI
# This file defines package-specific settings for automated testing and building

packages:
  # Frontend packages
  client:
    test-command: 'bun test'
    build-command: 'bun run build'
    typecheck: true
    timeout: 20
    coverage: true
    upload-artifacts: true
    dependencies:
      - 'shared'
      - 'ui'
      # - "api-client"  # Temporarily removed while api-client tests are disabled
    description: 'React client application'

  ui:
    test-command: 'bun run typecheck' # UI package primarily uses typecheck for validation
    build-command: 'bun run build'
    typecheck: false # Already covered by test-command
    timeout: 10
    coverage: false
    upload-artifacts: true
    dependencies:
      - 'shared'
    description: 'Component library with shadcn/ui'

  website:
    test-command: 'bun run typecheck'
    build-command: 'bun run build'
    typecheck: false
    timeout: 15
    coverage: false
    upload-artifacts: true
    dependencies:
      - 'ui'
      - 'shared'
    description: 'Marketing website'

  # Backend packages
  server:
    test-command: 'bun test'
    build-command: '' # Server doesn't need build step
    typecheck: true
    timeout: 15
    coverage: true
    upload-artifacts: false
    dependencies:
      - 'services'
      - 'storage'
      - 'schemas'
      - 'shared'
    description: 'Hono API server'

  services:
    test-command: 'bun test src/**/*.test.ts --timeout 5000'
    build-command: ''
    typecheck: true
    timeout: 15
    coverage: true
    upload-artifacts: false
    dependencies:
      - 'storage'
      - 'schemas'
      - 'shared'
    description: 'Business logic services'

  storage:
    test-command: 'bun test'
    build-command: ''
    typecheck: true
    timeout: 10
    coverage: true
    upload-artifacts: false
    dependencies:
      - 'schemas'
      - 'shared'
    description: 'SQLite storage layer'

  # Core packages
  schemas:
    test-command: 'bun test'
    build-command: ''
    typecheck: true
    timeout: 8
    coverage: true
    upload-artifacts: false
    dependencies:
      - 'shared'
    description: 'Zod schemas and types'

  shared:
    test-command: 'bun test'
    build-command: ''
    typecheck: true
    timeout: 8
    coverage: true
    upload-artifacts: false
    dependencies: []
    description: 'Shared utilities'

  # API packages
  # TEMPORARILY DISABLED: api-client tests failing due to database migration issue
  # TODO: Fix "table file_search_fts already exists" error and re-enable
  # api-client:
  #   test-command: "bun test"
  #   build-command: ""
  #   typecheck: true
  #   timeout: 12
  #   coverage: true
  #   upload-artifacts: false
  #   dependencies:
  #     - "schemas"
  #     - "shared"
  #   description: "Type-safe API client"

  # Configuration packages
  config:
    test-command: 'bun test'
    build-command: ''
    typecheck: true
    timeout: 5
    coverage: false
    upload-artifacts: false
    dependencies:
      - 'shared'
    description: 'Shared configuration'

  # Tools and CLI
  promptliano:
    test-command: 'bun test'
    build-command: 'bun run build'
    typecheck: true
    timeout: 10
    coverage: false
    upload-artifacts: true
    dependencies:
      - 'shared'
      - 'config'
    description: 'CLI package'

# Global settings
global:
  # Default timeout for packages not explicitly configured
  default-timeout: 15

  # Default commands
  default-test-command: 'bun test'
  default-build-command: "bun run build || echo 'No build script'"
  default-typecheck: true

  # Artifact settings
  artifact-retention-days: 7

  # Coverage settings
  coverage-threshold: 80

  # Patterns that trigger full monorepo rebuild
  root-change-patterns:
    - "^package\\.json$"
    - "^bun\\.lock"
    - "^\\.github/workflows/monorepo-ci\\.yml$"
    - "^\\.github/package-configs\\.yml$"
    - "^\\.github/actions/"

  # Package discovery settings
  packages-path: 'packages'

  # Test environment
  test-env:
    NODE_ENV: 'test'
    CI: 'true'
    SKIP_AI_TESTS: 'true'

# Build order for dependency resolution
build-order:
  - ['shared']
  - ['config', 'schemas']
  - ['storage'] # api-client temporarily removed
  - ['services']
  - ['server', 'ui']
  - ['client', 'website', 'promptliano']

# Package groups for parallel testing
test-groups:
  core:
    - 'shared'
    - 'config'
    - 'schemas'

  backend:
    - 'storage'
    - 'services'
    - 'server'
    # - "api-client"  # Temporarily disabled

  frontend:
    - 'ui'
    - 'client'
    - 'website'

  tools:
    - 'promptliano'
