/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DevSwaggerRouteImport } from './routes/dev-swagger'
import { Route as DevMermaidRouteImport } from './routes/dev-mermaid'
import { Route as DevMcpRouteImport } from './routes/dev-mcp'
import { Route as DevDrizzleRouteImport } from './routes/dev-drizzle'
import { Route as DeepResearchRouteImport } from './routes/deep-research'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueDashboardQueueIdRouteImport } from './routes/queue-dashboard.$queueId'
import { Route as DeepResearchResearchIdRouteImport } from './routes/deep-research_.$researchId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSwaggerRoute = DevSwaggerRouteImport.update({
  id: '/dev-swagger',
  path: '/dev-swagger',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMermaidRoute = DevMermaidRouteImport.update({
  id: '/dev-mermaid',
  path: '/dev-mermaid',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMcpRoute = DevMcpRouteImport.update({
  id: '/dev-mcp',
  path: '/dev-mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDrizzleRoute = DevDrizzleRouteImport.update({
  id: '/dev-drizzle',
  path: '/dev-drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepResearchRoute = DeepResearchRouteImport.update({
  id: '/deep-research',
  path: '/deep-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueDashboardQueueIdRoute = QueueDashboardQueueIdRouteImport.update({
  id: '/queue-dashboard/$queueId',
  path: '/queue-dashboard/$queueId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepResearchResearchIdRoute = DeepResearchResearchIdRouteImport.update({
  id: '/deep-research_/$researchId',
  path: '/deep-research/$researchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/deep-research': typeof DeepResearchRoute
  '/dev-drizzle': typeof DevDrizzleRoute
  '/dev-mcp': typeof DevMcpRoute
  '/dev-mermaid': typeof DevMermaidRoute
  '/dev-swagger': typeof DevSwaggerRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/deep-research/$researchId': typeof DeepResearchResearchIdRoute
  '/queue-dashboard/$queueId': typeof QueueDashboardQueueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/deep-research': typeof DeepResearchRoute
  '/dev-drizzle': typeof DevDrizzleRoute
  '/dev-mcp': typeof DevMcpRoute
  '/dev-mermaid': typeof DevMermaidRoute
  '/dev-swagger': typeof DevSwaggerRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/deep-research/$researchId': typeof DeepResearchResearchIdRoute
  '/queue-dashboard/$queueId': typeof QueueDashboardQueueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/chat': typeof ChatRoute
  '/deep-research': typeof DeepResearchRoute
  '/dev-drizzle': typeof DevDrizzleRoute
  '/dev-mcp': typeof DevMcpRoute
  '/dev-mermaid': typeof DevMermaidRoute
  '/dev-swagger': typeof DevSwaggerRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/prompts': typeof PromptsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/deep-research_/$researchId': typeof DeepResearchResearchIdRoute
  '/queue-dashboard/$queueId': typeof QueueDashboardQueueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/chat'
    | '/deep-research'
    | '/dev-drizzle'
    | '/dev-mcp'
    | '/dev-mermaid'
    | '/dev-swagger'
    | '/health'
    | '/login'
    | '/projects'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/setup'
    | '/deep-research/$researchId'
    | '/queue-dashboard/$queueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/chat'
    | '/deep-research'
    | '/dev-drizzle'
    | '/dev-mcp'
    | '/dev-mermaid'
    | '/dev-swagger'
    | '/health'
    | '/login'
    | '/projects'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/setup'
    | '/deep-research/$researchId'
    | '/queue-dashboard/$queueId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/chat'
    | '/deep-research'
    | '/dev-drizzle'
    | '/dev-mcp'
    | '/dev-mermaid'
    | '/dev-swagger'
    | '/health'
    | '/login'
    | '/projects'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/setup'
    | '/deep-research_/$researchId'
    | '/queue-dashboard/$queueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  ChatRoute: typeof ChatRoute
  DeepResearchRoute: typeof DeepResearchRoute
  DevDrizzleRoute: typeof DevDrizzleRoute
  DevMcpRoute: typeof DevMcpRoute
  DevMermaidRoute: typeof DevMermaidRoute
  DevSwaggerRoute: typeof DevSwaggerRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  PromptsRoute: typeof PromptsRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  DeepResearchResearchIdRoute: typeof DeepResearchResearchIdRoute
  QueueDashboardQueueIdRoute: typeof QueueDashboardQueueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-swagger': {
      id: '/dev-swagger'
      path: '/dev-swagger'
      fullPath: '/dev-swagger'
      preLoaderRoute: typeof DevSwaggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-mermaid': {
      id: '/dev-mermaid'
      path: '/dev-mermaid'
      fullPath: '/dev-mermaid'
      preLoaderRoute: typeof DevMermaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-mcp': {
      id: '/dev-mcp'
      path: '/dev-mcp'
      fullPath: '/dev-mcp'
      preLoaderRoute: typeof DevMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-drizzle': {
      id: '/dev-drizzle'
      path: '/dev-drizzle'
      fullPath: '/dev-drizzle'
      preLoaderRoute: typeof DevDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-research': {
      id: '/deep-research'
      path: '/deep-research'
      fullPath: '/deep-research'
      preLoaderRoute: typeof DeepResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue-dashboard/$queueId': {
      id: '/queue-dashboard/$queueId'
      path: '/queue-dashboard/$queueId'
      fullPath: '/queue-dashboard/$queueId'
      preLoaderRoute: typeof QueueDashboardQueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-research_/$researchId': {
      id: '/deep-research_/$researchId'
      path: '/deep-research/$researchId'
      fullPath: '/deep-research/$researchId'
      preLoaderRoute: typeof DeepResearchResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  ChatRoute: ChatRoute,
  DeepResearchRoute: DeepResearchRoute,
  DevDrizzleRoute: DevDrizzleRoute,
  DevMcpRoute: DevMcpRoute,
  DevMermaidRoute: DevMermaidRoute,
  DevSwaggerRoute: DevSwaggerRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  PromptsRoute: PromptsRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  DeepResearchResearchIdRoute: DeepResearchResearchIdRoute,
  QueueDashboardQueueIdRoute: QueueDashboardQueueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
