# .github/workflows/api-client-release-workflow.yml

name: API Client CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'packages/api-client/**'
    tags:
      - 'api-client-v*.*.*'
  pull_request:
    branches: [main]
    paths:
      - 'packages/api-client/**'

jobs:
  api-client-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install api-client dependencies
        run: cd packages/api-client && bun install

      # TODO implement tests, this requires having a running server
      # - name: Run api-client tests
      #   run: |
      #     echo "🧪 Running API Client Package Tests..."
      #     cd packages/api-client && bun run test

      - name: Build api-client package
        run: |
          echo "🔨 Building API Client Package..."
          cd packages/api-client && bun run build

      - name: Dry run publish (non-tag builds)
        if: ${{ !startsWith(github.ref, 'refs/tags/api-client-v') }}
        run: |
          echo "🔍 Running publish dry run..."
          cd packages/api-client && bun run publish:dry

  publish-api-client:
    needs: [api-client-ci]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/api-client-v')
    permissions:
      contents: read
      id-token: write # Required for npm provenance
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js for npm publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install api-client dependencies
        run: cd packages/api-client && bun install

      - name: Build api-client package
        run: |
          echo "🔨 Building API Client Package for Release..."
          cd packages/api-client && bun run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "📦 Publishing API Client Package to npm..."
          cd packages/api-client && npm publish --provenance