# .github/workflows/release-binaries.yml

name: Build and Release Binaries

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-build-and-release:
    name: Test, Build, and Release Binaries
    runs-on: ubuntu-latest
    # Add the permissions block here
    permissions:
      contents: write # Required to write to releases (upload assets)
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Build binaries
        run: bun run build-binaries

      - name: Upload Release Assets
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive binary artifacts for non-release builds
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ github.sha }}
          path: |
            dist/*.zip
