# .github/workflows/release-binaries.yml

name: Build and Release Binaries

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-build-and-release:
    name: Test, Build, and Release Binaries
    runs-on: ubuntu-latest
    # Add the permissions block here
    permissions:
      contents: write # Required to write to releases (upload assets)
    steps:
      - name: Checkout repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Bun and dependencies
        uses: ./.github/actions/setup-bun
        with:
          bun-version: 'latest'
          cache-key-suffix: -release-binaries

      - name: Run shared tests
        run: bun test:shared

      - name: Build UI package
        run: |
          cd packages/ui
          NODE_ENV=production bun run build

      - name: Build binaries
        run: bun run build-binaries

      - name: Upload Release Assets
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive binary artifacts for non-release builds
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ./.github/actions/optimized-artifact-upload
        with:
          artifact-name: release-binaries-${{ github.sha }}
          artifact-path: dist/*.zip
          upload-condition: always
          retention-days: 90  # Long retention for release artifacts
          compress: false  # Already compressed
          include-git-info: true
