name: Root Binary Build CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-root-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Test root build
        run: bun run build 