name: Server CI
on:
  push:
    branches: [main]
    # paths:
    #   - 'server/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/server/**'

jobs:
  server-ci:
    runs-on: ubuntu-latest
    # env:
    #   DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}
    #   STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    #   STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install shared dependencies
        run: cd packages/shared && bun install

      - name: Install server dependencies
        run: cd packages/server && bun install

    #   - name: Run E2E tests
    #     run: |
    #       echo "🔄 Running E2E Tests..."
    #       cd server && bun run test:e2e

  # deploy:
  #   needs: [test-server]
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Deploy application
  #       run: echo "Add your deployment steps here"
